import './globals.css'
import { PT_Serif } from 'next/font/google'
import Header from './components/header.js'
import Footer from './components/footer.js'

const pt_serif = PT_Serif({
  subsets: ['latin'],
  weight: '400',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={pt_serif.className}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
